<a href="https://colab.research.google.com/github/vikpy/AISem3/blob/master/HW/HomeWork2_Tensor_Vector_Binary_Tree.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Q1. Difference and Similarity between tensors and vectors 

**Difference**: Tensors are n indices and mxn components in a mth dimensional space and nth rank tensor. Tensors are just generalization of scalar representation of object. Tensors have certain set of Linear operations or Transformations. 
A vector is an object that has both a magnitude and a direction. Thus vector can be also be defined using a fixed set of basis vector as well. 

**Similarirty**: As mentioned before tensors have certain set transformations. Based on rank of the tensor it can be classified as follows:
Objects that transform like **zeroth-rank tensors** are called scalars, those that transform like **first-rank tensors** are called vectors, and those that transform like **second-rank tensors** are called matrices. In tensor notation, a vector v would be written v_i, where i=1, ..., m, and matrix is a tensor of type (1,1), which would be written a_i^j in tensor notation.

Following image carves out the difference between difference objects used on Machine Learning very clearly from computer science perspective. 

![Scalar, Vector, Matrix, Tensor](https://hadrienj.github.io/assets/images/2.1/scalar-vector-matrix-tensor.png)

Reference: [Tensors(Wolfram Mathworld)](https://mathworld.wolfram.com/Tensor.html)




# Q2. Difference between tensor data (tensorflow)object vs ndarray(Numpy) including operations , execution time and other relevant properties



References:

1. https://www.tensorflow.org/guide/tensor

2. https://machinelearningmastery.com/introduction-to-tensors-for-machine-learning/

3. https://simplyml.com/linear-algebra-shootout-numpy-vs-theano-vs-tensorflow-2/


LINK TO THE PRESENTATION:

https://github.com/vikpy/AISem3/blob/master/HW/tensorflow_numpy.pdf

In [3]:
import tensorflow as tf
import numpy as np



numpy.ndarray

We will make 3 3 3 tensor and compare operations execution in tensorflow object

In [26]:
# In tensorflow

a_tf = tf.constant([[1, 2],
                 [3, 4]])
b_tf = tf.constant([[2, -1],
                 [1, 7]]) # Could have also said `tf.ones([2,2])`

print(tf.add(a_tf, b_tf), "\n")
print(tf.multiply(a_tf, b_tf), "\n")
print(tf.matmul(a_tf, b_tf), "\n")

tf.Tensor(
[[ 3  1]
 [ 4 11]], shape=(2, 2), dtype=int32) 

tf.Tensor(
[[ 2 -2]
 [ 3 28]], shape=(2, 2), dtype=int32) 

tf.Tensor(
[[ 4 13]
 [10 25]], shape=(2, 2), dtype=int32) 



In [27]:
# Alternatively
print(a_tf + b_tf, "\n") # element-wise addition
print(a_tf * b_tf, "\n") # element-wise multiplication
print(a_tf @ b_tf, "\n") # matrix multiplication

tf.Tensor(
[[ 3  1]
 [ 4 11]], shape=(2, 2), dtype=int32) 

tf.Tensor(
[[ 2 -2]
 [ 3 28]], shape=(2, 2), dtype=int32) 

tf.Tensor(
[[ 4 13]
 [10 25]], shape=(2, 2), dtype=int32) 



In [28]:
from numpy import np
a_np = np.array([[1, 2],
          [3, 4]])
b_np = np.array(
     [[2, -1],
     [1, 7]] 
)
# Tensor operations similar to tf still works for numpy
print(a_np + b_np, type(a_np + b_np),  "\n") # element-wise addition  
print(a_np * b_np,type(a_np + b_np), "\n") # element-wise multiplication
print(a_np @ b_np,type(a_np + b_np), "\n") # matrix multiplication

[[ 3  1]
 [ 4 11]] <class 'numpy.ndarray'> 

[[ 2 -2]
 [ 3 28]] <class 'numpy.ndarray'> 

[[ 4 13]
 [10 25]] <class 'numpy.ndarray'> 



We can also try tensor division

In [29]:
print(a_np/b_np,type(a_np/b_np), "\n")  # In numpy 
print(a_tf/b_tf,type(a_tf/b_tf), "\n")  # In tensorflow 

[[ 0.5        -2.        ]
 [ 3.          0.57142857]] <class 'numpy.ndarray'> 

tf.Tensor(
[[ 0.5        -2.        ]
 [ 3.          0.57142857]], shape=(2, 2), dtype=float64) <class 'tensorflow.python.framework.ops.EagerTensor'> 



In [35]:
#Tensor Dot Product using np array 
c_np = np.tensordot(a_np, b_np, axes=0)
print(c_np, type(c_np))

[[[[ 2 -1]
   [ 1  7]]

  [[ 4 -2]
   [ 2 14]]]


 [[[ 6 -3]
   [ 3 21]]

  [[ 8 -4]
   [ 4 28]]]] <class 'numpy.ndarray'>


In [36]:
#tensor dot is similar in tensorflow as well
c_tf = tf.tensordot(a_tf, b_tf, axes=0)
print(c_tf, type(c_tf))

tf.Tensor(
[[[[ 2 -1]
   [ 1  7]]

  [[ 4 -2]
   [ 2 14]]]


 [[[ 6 -3]
   [ 3 21]]

  [[ 8 -4]
   [ 4 28]]]], shape=(2, 2, 2, 2), dtype=int32) <class 'tensorflow.python.framework.ops.EagerTensor'>


We will asses the speed for tensorflow and numpy 

In [44]:
import numpy
import timeit
A = numpy.random.rand(10, 10).astype(numpy.float32)
B = numpy.random.rand(10, 10).astype(numpy.float32)

timer = timeit.Timer("numpy.dot(A, B)", "import numpy; from __main__ import A, B")
numpy_times_list = timer.repeat()
min(numpy_times_list)

1.456392951999078

In [57]:
import tensorflow as tf

A = tf.constant(A)
B = tf.constant(B)

timer = timeit.Timer("tf.matmul(A, B)", setup="import tensorflow as tf; from __main__ import A, B")
tensorflow_times_list = timer.repeat()
min(tensorflow_times_list)

16.763378783000007

# Q.3 Implement a complete binary tree with 5 implementations of a graph

In [70]:
# different implementations of different Complete Binary tree structures for A B C D E F G H I J

tree1 = [
    ['A' , 'B', 'C'],

    ['B', 'D', 'E'],

    ['C', 'F', 'G'],

    ['D', 'H', 'I'],

    ['E', 'J'],
    
    ['H' ],

    ['I' ],

    ['J'],

     ['F'],

     ['G' ]

]


tree2 = [
    ['A',  [ 'B', 'C'] ] ,

    ['B', [ 'D', 'E'] ],

    ['C', [ 'F', 'G'] ],

    ['D', ['H', 'I'] ],

    ['E', [ 'J']],


    ['H' ,[]],

    ['I' ,[]],

    ['J' ,[]],

     ['F' ,[]],

     ['G',[]]

]


tree3 = [
    ['A',  ( 'B', 'C') ] ,

    ['B', ( 'D', 'E') ],

    ['C', ( 'F', 'G') ],

    ['D', ('H', 'I') ],

    ['E', ('J') ],

    ['H' ,()] ,

    ['I' ,()],

    ['J' ,() ],

     ['F' ,() ],

     ['G',()]
]


tree4 = (
    ['A',  [ 'B', 'C'] ] ,

    ['B', [ 'D', 'E'] ],

    ['C', [ 'F', 'G'] ],

    ['D', ['H', 'I'] ],

    ['E', [ 'J']],

    ['H' ,[]],

    ['I' ,[]],

    ['J' ,[]],

     ['F' ,[]],

     ['G',[]]

)


tree5 = {
    'A':  [ 'B', 'C']  ,

    'B': [ 'D', 'E'] ,

    'C': [ 'F', 'G'] ,

    'D': ['H', 'I'] ,

    'E': ['J'],

    'H' :[],

    'I' :[],

    'J' :[],

     'F' :[],

     'G':[]
}




def createTree(*nodes):
  '''
  pending
  '''


#Q4. Implement DFS in the binary tree to search for a node based on user input

In [68]:
def dfs(visited, graph, node):
    '''
    Recursive function implementing DFS 
    '''
    if node not in visited:
        print(f'Node Name {node}')
        visited.add(node)
        for neighbour in graph[node]:
            print(f'Neighbor of Node: {node} is {neighbour}')
            dfs(visited, graph, neighbour)
visited = set()
print("-"*100)
print("Traversal:")
dfs(visited, tree5, 'A')
print("-"*100)

----------------------------------------------------------------------------------------------------
Traversal:
Node Name A
Neighbor of Node: A is B
Node Name B
Neighbor of Node: B is D
Node Name D
Neighbor of Node: D is H
Node Name H
Neighbor of Node: D is I
Node Name I
Neighbor of Node: B is E
Node Name E
Neighbor of Node: E is J
Node Name J
Neighbor of Node: A is C
Node Name C
Neighbor of Node: C is F
Node Name F
Neighbor of Node: C is G
Node Name G
----------------------------------------------------------------------------------------------------
