<a href="https://colab.research.google.com/github/vikpy/AISem3/blob/master/CW/Classwork_dataframe_task.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1) Read any csv file or any json file in df with 6 cols atleast and 1000 rows

2) Split the file into test and train using pandas with a user input for the ratio of split

3) Traverse each row and each column of the dataframe


4) Write a function to query if a values exists in the dataframe and return its complete column and complete row separately

5) Apply 3 and 4 to Train and Test

6) From the list of columns , construct all combinations of 3 values and for each combination combine their row values as  a combined column

# Q1. Read any csv file or any json file in df with 6 cols atleast and 1000 rows

In [1]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv("/content/sample_data/california_housing_train.csv")
df.head()

longitude  latitude  ...  median_income  median_house_value
0    -114.31     34.19  ...         1.4936             66900.0
1    -114.47     34.40  ...         1.8200             80100.0
2    -114.56     33.69  ...         1.6509             85700.0
3    -114.57     33.64  ...         3.1917             73400.0
4    -114.57     33.57  ...         1.9250             65500.0

[5 rows x 9 columns]

In [4]:
df.shape

(17000, 9)

# Q2. Split the file into test and train using pandas with a user input for the ratio of split

In [6]:
train_ratio = float(input("Give the train ratio value:"))
train_value = int(train_ratio*df.shape[0])
train = df.iloc[:train_value,:]
test = df.iloc[train_value:,:]

Give the train ratio value:0.8


# Q3. Traverse each row and each column of the dataframe

In [8]:
# Printing the rows 
for row in df.values:
  print(row)

Streaming output truncated to the last 5000 lines.
  2.4300e+02  4.0682e+00  1.9620e+05]
[-1.22140e+02  3.75000e+01  4.60000e+01  3.00000e+01  4.00000e+00
  1.30000e+01  5.00000e+00  1.50001e+01  5.00001e+05]
[-1.2214e+02  3.7480e+01  3.6000e+01  1.2100e+03  2.3600e+02  9.8100e+02
  2.3900e+02  4.0039e+00  1.4890e+05]
[-1.2214e+02  3.7470e+01  3.7000e+01  3.3730e+03  8.1500e+02  2.9090e+03
  7.0500e+02  2.8868e+00  1.5660e+05]
[-1.2214e+02  3.7470e+01  3.6000e+01  2.0810e+03  4.1200e+02  1.9310e+03
  3.7300e+02  3.7917e+00  1.6060e+05]
[-1.2214e+02  3.7460e+01  2.7000e+01  5.5800e+03  2.0090e+03  4.1650e+03
  1.7630e+03  2.4375e+00  1.8900e+05]
[-1.22140e+02  3.74500e+01  5.20000e+01  3.84100e+03  5.37000e+02
  1.39100e+03  5.40000e+02  7.86470e+00  5.00001e+05]
[-1.22140e+02  3.74500e+01  4.80000e+01  2.07400e+03  2.97000e+02
  7.00000e+02  2.79000e+02  8.70510e+00  5.00001e+05]
[-1.22140e+02  3.74400e+01  5.20000e+01  3.11700e+03  4.68000e+02
  1.11400e+03  4.21000e+02  6.67560e+00  

In [10]:
# Printing the rows 
for column in df.columns.values:
  print(column)

longitude
latitude
housing_median_age
total_rooms
total_bedrooms
population
households
median_income
median_house_value


In [11]:
for column in df.columns.values:
  for row in df[column].values:
    print(f"Value {row} in Column {column}")

Streaming output truncated to the last 5000 lines.
Value 154300.0 in Column median_house_value
Value 92000.0 in Column median_house_value
Value 237600.0 in Column median_house_value
Value 146900.0 in Column median_house_value
Value 107200.0 in Column median_house_value
Value 107000.0 in Column median_house_value
Value 98700.0 in Column median_house_value
Value 130400.0 in Column median_house_value
Value 113200.0 in Column median_house_value
Value 118800.0 in Column median_house_value
Value 156800.0 in Column median_house_value
Value 297600.0 in Column median_house_value
Value 327800.0 in Column median_house_value
Value 142500.0 in Column median_house_value
Value 142400.0 in Column median_house_value
Value 67500.0 in Column median_house_value
Value 106300.0 in Column median_house_value
Value 130600.0 in Column median_house_value
Value 322400.0 in Column median_house_value
Value 145400.0 in Column median_house_value
Value 157300.0 in Column median_house_value
Value 136500.0 in Column med

#Q4. Write a function to query if a values exists in the dataframe and return its complete column and complete row separately

In [47]:
def queryDf(df, value):
  row_colum = set()
  for column in df.columns.values:
    for row in df[column].index:
      if df.loc[row,column] == value :
        row_colum.add((row, column))
  return row_colum

queryDf(df, 34.19)

{(0, 'latitude'),
 (324, 'latitude'),
 (2017, 'latitude'),
 (4941, 'latitude'),
 (5037, 'latitude'),
 (5131, 'latitude'),
 (5132, 'latitude'),
 (5133, 'latitude'),
 (5233, 'latitude'),
 (5234, 'latitude'),
 (5330, 'latitude'),
 (5331, 'latitude'),
 (5426, 'latitude'),
 (5427, 'latitude'),
 (5428, 'latitude'),
 (5513, 'latitude'),
 (5601, 'latitude'),
 (5704, 'latitude'),
 (6008, 'latitude'),
 (6009, 'latitude'),
 (6010, 'latitude'),
 (6780, 'latitude'),
 (6781, 'latitude'),
 (6782, 'latitude'),
 (6913, 'latitude'),
 (6914, 'latitude'),
 (7045, 'latitude'),
 (7046, 'latitude'),
 (7047, 'latitude'),
 (7171, 'latitude'),
 (7172, 'latitude'),
 (7244, 'latitude'),
 (7245, 'latitude'),
 (7246, 'latitude'),
 (7247, 'latitude'),
 (7355, 'latitude'),
 (7465, 'latitude'),
 (7466, 'latitude'),
 (7587, 'latitude'),
 (7696, 'latitude'),
 (7697, 'latitude'),
 (7698, 'latitude'),
 (7779, 'latitude'),
 (7780, 'latitude'),
 (7781, 'latitude'),
 (7863, 'latitude'),
 (7864, 'latitude'),
 (7865, 'latitude

#Q5. Do 3 and 4 to train and test


In [48]:
# For train
for column in train.columns.values:
  for row in train[column].values:
    print(f"Value {row} in Column {column}")   

Streaming output truncated to the last 5000 lines.
Value 221800.0 in Column median_house_value
Value 245400.0 in Column median_house_value
Value 259600.0 in Column median_house_value
Value 500001.0 in Column median_house_value
Value 500001.0 in Column median_house_value
Value 500001.0 in Column median_house_value
Value 500001.0 in Column median_house_value
Value 500001.0 in Column median_house_value
Value 500001.0 in Column median_house_value
Value 220100.0 in Column median_house_value
Value 233200.0 in Column median_house_value
Value 136100.0 in Column median_house_value
Value 333700.0 in Column median_house_value
Value 320500.0 in Column median_house_value
Value 308400.0 in Column median_house_value
Value 323100.0 in Column median_house_value
Value 240000.0 in Column median_house_value
Value 230400.0 in Column median_house_value
Value 199800.0 in Column median_house_value
Value 213200.0 in Column median_house_value
Value 205300.0 in Column median_house_value
Value 191100.0 in Column 

In [49]:
# For test
for column in test.columns.values:
  for row in test[column].values:
    print(f"Value {row} in Column {column}")   

Streaming output truncated to the last 5000 lines.
Value 3.6393 in Column median_income
Value 4.5 in Column median_income
Value 4.0804 in Column median_income
Value 3.6321 in Column median_income
Value 3.4091 in Column median_income
Value 3.5125 in Column median_income
Value 2.9219 in Column median_income
Value 2.3946 in Column median_income
Value 2.2672 in Column median_income
Value 4.5824 in Column median_income
Value 3.0208 in Column median_income
Value 2.9 in Column median_income
Value 1.475 in Column median_income
Value 2.2208 in Column median_income
Value 2.1705 in Column median_income
Value 2.75 in Column median_income
Value 4.0018 in Column median_income
Value 1.191 in Column median_income
Value 1.1667 in Column median_income
Value 2.5938 in Column median_income
Value 0.8056 in Column median_income
Value 2.6447 in Column median_income
Value 5.033 in Column median_income
Value 5.5184 in Column median_income
Value 3.9833 in Column median_income
Value 2.9405 in Column median_incom

In [50]:
queryDf(train, 34.19)

{(0, 'latitude'),
 (324, 'latitude'),
 (2017, 'latitude'),
 (4941, 'latitude'),
 (5037, 'latitude'),
 (5131, 'latitude'),
 (5132, 'latitude'),
 (5133, 'latitude'),
 (5233, 'latitude'),
 (5234, 'latitude'),
 (5330, 'latitude'),
 (5331, 'latitude'),
 (5426, 'latitude'),
 (5427, 'latitude'),
 (5428, 'latitude'),
 (5513, 'latitude'),
 (5601, 'latitude'),
 (5704, 'latitude'),
 (6008, 'latitude'),
 (6009, 'latitude'),
 (6010, 'latitude'),
 (6780, 'latitude'),
 (6781, 'latitude'),
 (6782, 'latitude'),
 (6913, 'latitude'),
 (6914, 'latitude'),
 (7045, 'latitude'),
 (7046, 'latitude'),
 (7047, 'latitude'),
 (7171, 'latitude'),
 (7172, 'latitude'),
 (7244, 'latitude'),
 (7245, 'latitude'),
 (7246, 'latitude'),
 (7247, 'latitude'),
 (7355, 'latitude'),
 (7465, 'latitude'),
 (7466, 'latitude'),
 (7587, 'latitude'),
 (7696, 'latitude'),
 (7697, 'latitude'),
 (7698, 'latitude'),
 (7779, 'latitude'),
 (7780, 'latitude'),
 (7781, 'latitude'),
 (7863, 'latitude'),
 (7864, 'latitude'),
 (7865, 'latitude

In [51]:
queryDf(test, 34.19)

set()

# Q6.From the list of columns , construct all combinations of 3 values and for each combination combine their row values as  a combined column

In [64]:
combinations = set()
for value1 in df.columns.values:
  for value2 in df.columns.values:
    for value3 in df.columns.values:
      if value1 != value2 and value1 != value3 and value2 != value3:
        combinations.add((value1, value2, value3))

combinations

{('households', 'housing_median_age', 'latitude'),
 ('households', 'housing_median_age', 'longitude'),
 ('households', 'housing_median_age', 'median_house_value'),
 ('households', 'housing_median_age', 'median_income'),
 ('households', 'housing_median_age', 'population'),
 ('households', 'housing_median_age', 'total_bedrooms'),
 ('households', 'housing_median_age', 'total_rooms'),
 ('households', 'latitude', 'housing_median_age'),
 ('households', 'latitude', 'longitude'),
 ('households', 'latitude', 'median_house_value'),
 ('households', 'latitude', 'median_income'),
 ('households', 'latitude', 'population'),
 ('households', 'latitude', 'total_bedrooms'),
 ('households', 'latitude', 'total_rooms'),
 ('households', 'longitude', 'housing_median_age'),
 ('households', 'longitude', 'latitude'),
 ('households', 'longitude', 'median_house_value'),
 ('households', 'longitude', 'median_income'),
 ('households', 'longitude', 'population'),
 ('households', 'longitude', 'total_bedrooms'),
 ('hous

In [65]:
for values in combinations:
  print('*'*100)
  print(values)
  print(np.array(df[list(values)]))

****************************************************************************************************
('housing_median_age', 'longitude', 'population')
[[  15.   -114.31 1015.  ]
 [  19.   -114.47 1129.  ]
 [  17.   -114.56  333.  ]
 ...
 [  17.   -124.3  1244.  ]
 [  19.   -124.3  1298.  ]
 [  52.   -124.35  806.  ]]
****************************************************************************************************
('households', 'total_bedrooms', 'longitude')
[[ 472.   1283.   -114.31]
 [ 463.   1901.   -114.47]
 [ 117.    174.   -114.56]
 ...
 [ 456.    531.   -124.3 ]
 [ 478.    552.   -124.3 ]
 [ 270.    300.   -124.35]]
****************************************************************************************************
('median_income', 'latitude', 'total_rooms')
[[1.4936e+00 3.4190e+01 5.6120e+03]
 [1.8200e+00 3.4400e+01 7.6500e+03]
 [1.6509e+00 3.3690e+01 7.2000e+02]
 ...
 [3.0313e+00 4.1840e+01 2.6770e+03]
 [1.9797e+00 4.1800e+01 2.6720e+03]
 [3.0147e+00 4.0540e+01 1.8200e+03]